In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv("/content/sample_data/Social_Network_Ads.csv")
df.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

# Preprocessing

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
df.shape

(400, 5)

In [7]:
df.describe().transpose()

count          mean           std         min          25%  \
User ID          400.0  1.569154e+07  71658.321581  15566689.0  15626763.75   
Age              400.0  3.765500e+01     10.482877        18.0        29.75   
EstimatedSalary  400.0  6.974250e+04  34096.960282     15000.0     43000.00   
Purchased        400.0  3.575000e-01      0.479864         0.0         0.00   

                        50%         75%         max  
User ID          15694341.5  15750363.0  15815236.0  
Age                    37.0        46.0        60.0  
EstimatedSalary     70000.0     88000.0    150000.0  
Purchased               0.0         1.0         1.0

In [8]:
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [9]:
df.size

2000

In [13]:
X = df.iloc[:,[2,3]].values
y = df.iloc[:,4].values
print(X)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 20)

In [15]:
regression = LogisticRegression()
regression.fit(X_train, y_train)

LogisticRegression()

In [17]:
y_pred = regression.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.5625

In [24]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[-0.80276277  0.44295604]
 [-0.70800656  1.43671337]
 [-0.23422551 -0.5508013 ]
 [ 0.90284902  1.16568865]
 [-1.0870314   0.4730699 ]
 [-0.89751898 -1.09285075]
 [-0.51849414  0.95489164]
 [ 1.47138628  0.41284218]
 [-1.46605624  0.38272832]
 [-1.75032487 -1.48433091]
 [-0.42373793 -1.12296461]
 [ 0.99760523 -1.00250917]
 [-0.23422551 -1.24342004]
 [ 0.90284902 -1.36387548]
 [ 0.52382418  1.82819354]
 [-1.65556866 -0.97239532]
 [ 0.14479933  0.20204517]
 [ 0.05004312 -0.5508013 ]
 [-0.61325035  0.17193131]
 [-0.32898172 -0.76159831]
 [-0.1394693   1.49694109]
 [ 1.37663007 -1.42410319]
 [-0.23422551 -1.36387548]
 [-0.80276277 -0.21954885]
 [ 0.90284902 -1.30364776]
 [-0.23422551  0.59352533]
 [ 0.99760523  1.88842125]
 [-0.61325035 -1.51444477]
 [-1.37130003 -0.06897956]
 [-0.61325035  0.62363919]
 [-1.65556866 -1.36387548]
 [-1.18178761 -1.06273689]
 [ 0.7133366  -1.39398934]
 [ 0.80809281 -1.36387548]
 [-1.56081245 -1.57467249]
 [ 0.33431175 -1.15307847]
 [ 0.80809281 -1.09285075]
 

In [25]:
regression = LogisticRegression(random_state = 0)
regression.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [27]:
y_pred = regression.predict(X_test)
print(y_pred)

[0 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0
 0 1 1 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1
 0 1 0 0 1 0]


In [28]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [29]:
print(cm)

[[43  2]
 [ 9 26]]


In [30]:
TP = cm[0][0]
FN = cm[0][1]
FP = cm[1][0]
TN = cm[1][1]
print(f"True Positive : {TP}")
print(f"True Negative : {TN}")
print(f"False Positive : {FP}")
print(f"False Negative : {FN}")

True Positive : 43
True Negative : 26
False Positive : 9
False Negative : 2


In [31]:
accuracy = (TP + TN) / (TP + TN + FP + FN)
precision = TP / (TP + FP)
recall = TP / (TP + FN)
error = (FN + FP) / (TP + TN + FP + FN)
error_rate = 1 - accuracy

print(f"Accuracy : {accuracy}")
print(f"Precision : {precision}")
print(f"Recall : {recall}")
print(f"Error : {error}")
print(f"Error_rate : {error_rate}")

Accuracy : 0.8625
Precision : 0.8269230769230769
Recall : 0.9555555555555556
Error : 0.1375
Error_rate : 0.13749999999999996
